#!/usr/bin/env node
/**
 * Generates stories/*.stories.js from components/* folders.
 * HTML/CSS content HMR via import.meta.glob + preview CSS imports.
 * Stories enable Autodocs, source code, and interactive play hooks.
 */
import fs from "node:fs";
import path from "node:path";
import {
  root,
  componentsDir,
  listComponents,
  categorize,
  toPascalCase,
} from "./lib/components.mjs";

const storiesDir = path.join(root, "stories");

/** Interactive demos that need play-time wiring (beyond render.js). */
const PLAY_COMPONENTS = new Set(["dialog", "canvas", "template", "output", "megaform"]);

function readSource(name) {
  const htmlPath = path.join(componentsDir, name, `${name}.html`);
  if (!fs.existsSync(htmlPath)) return "";
  return fs.readFileSync(htmlPath, "utf8").trim();
}

function writeStoriesFile(fileName, title, names, category) {
  const lines = [
    `/* AUTO-GENERATED by scripts/generate-stories.mjs — do not edit by hand */`,
    `import { renderComponent, playComponent } from "./render.js";`,
    ``,
    `export default {`,
    `  title: ${JSON.stringify(title)},`,
    `  tags: ["autodocs"],`,
    `  parameters: {`,
    `    layout: "fullscreen",`,
    `    docs: {`,
    `      description: {`,
    `        component: ${JSON.stringify(
      `${title} components from deml-ui. Source: components/<name>/<name>.html + .css`
    )},`,
    `      },`,
    `    },`,
    `  },`,
    `};`,
    ``,
  ];

  for (const name of names) {
    const source = readSource(name);
    const hasPlay = PLAY_COMPONENTS.has(name);
    const sourceLiteral = JSON.stringify(source);

    lines.push(
      `export const ${toPascalCase(name)} = {`,
      `  name: ${JSON.stringify(name)},`,
      `  tags: ["autodocs", ${JSON.stringify(`category:${category}`)}],`,
      `  render: () => renderComponent(${JSON.stringify(name)}),`,
      ...(hasPlay
        ? [
            `  play: async ({ canvasElement }) => {`,
            `    await playComponent(${JSON.stringify(name)}, canvasElement);`,
            `  },`,
          ]
        : []),
      `  parameters: {`,
      `    docs: {`,
      `      description: {`,
      `        story: ${JSON.stringify(
        `**${name}** — \`components/${name}/${name}.html\` + \`${name}.css\``
      )},`,
      `      },`,
      `      source: {`,
      `        language: "html",`,
      `        code: ${sourceLiteral},`,
      `        type: "code",`,
      `      },`,
      `    },`,
      `  },`,
      `};`,
      ``
    );
  }

  fs.writeFileSync(path.join(storiesDir, fileName), lines.join("\n"));
  return names.length;
}

const names = listComponents();
const { shellNames, formNames, componentNames } = categorize(names);

fs.mkdirSync(storiesDir, { recursive: true });

for (const file of fs.readdirSync(storiesDir)) {
  // Keep hand-written MDX; only regenerate *.stories.js
  if (file.endsWith(".stories.js")) {
    fs.unlinkSync(path.join(storiesDir, file));
  }
}

const shellCount = writeStoriesFile(
  "shell.stories.js",
  "Shell",
  shellNames,
  "shell"
);
const formCount = writeStoriesFile(
  "forms.stories.js",
  "Forms",
  formNames,
  "forms"
);
const componentCount = writeStoriesFile(
  "components.stories.js",
  "Components",
  componentNames,
  "components"
);

console.log(
  `Wrote ${shellCount} shell + ${formCount} forms + ${componentCount} component stories → stories/`
);
