#!/usr/bin/env node
/**
 * Generates stories/*.stories.js from components/* folders.
 * HTML/CSS content HMR via import.meta.glob + preview CSS imports.
 * Re-run when you add or remove a component folder (npm run storybook does this).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const componentsDir = path.join(root, "components");
const storiesDir = path.join(root, "stories");

const SHELL = [
  "skip-link",
  "site-header",
  "navbar",
  "gallery",
  "site-footer",
];

/** Form atoms + composition (order used in Forms stories). */
const FORMS_ORDER = [
  "input-text",
  "input-email",
  "input-password",
  "input-tel",
  "input-url",
  "input-search",
  "input-number",
  "input-range",
  "input-color",
  "input-date",
  "input-time",
  "input-datetime-local",
  "input-month",
  "input-week",
  "checkbox-newsletter",
  "checkbox-updates",
  "radio-free",
  "radio-pro",
  "radio-team",
  "select",
  "datalist",
  "input-file",
  "input-hidden",
  "input-image",
  "textarea",
  "output",
  "progress",
  "meter",
  "button-submit",
  "button-reset",
  "button",
  "input-submit",
  "input-reset",
  "input-button",
  "megaform",
];

function exportName(kebab) {
  return kebab
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function writeStoriesFile(fileName, title, names) {
  const lines = [
    `/* AUTO-GENERATED by scripts/generate-stories.mjs — do not edit by hand */`,
    `import { renderComponent } from "./render.js";`,
    ``,
    `export default {`,
    `  title: ${JSON.stringify(title)},`,
    `  parameters: { layout: "fullscreen" },`,
    `};`,
    ``,
  ];

  for (const name of names) {
    lines.push(
      `export const ${exportName(name)} = {`,
      `  name: ${JSON.stringify(name)},`,
      `  render: () => renderComponent(${JSON.stringify(name)}),`,
      `  parameters: {`,
      `    docs: { description: { story: "Source: components/${name}/${name}.html + ${name}.css" } },`,
      `  },`,
      `};`,
      ``
    );
  }

  const outFile = path.join(storiesDir, fileName);
  fs.writeFileSync(outFile, lines.join("\n"));
  return names.length;
}

const names = fs
  .readdirSync(componentsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .filter((name) =>
    fs.existsSync(path.join(componentsDir, name, `${name}.html`))
  );

const formSet = new Set(FORMS_ORDER);
const shellNames = SHELL.filter((n) => names.includes(n));
const formNames = FORMS_ORDER.filter((n) => names.includes(n));
const componentNames = names
  .filter((n) => !SHELL.includes(n) && !formSet.has(n))
  .sort((a, b) => a.localeCompare(b));

fs.mkdirSync(storiesDir, { recursive: true });

for (const file of fs.readdirSync(storiesDir)) {
  if (file.endsWith(".stories.js")) {
    fs.unlinkSync(path.join(storiesDir, file));
  }
}

const shellCount = writeStoriesFile("shell.stories.js", "Shell", shellNames);
const formCount = writeStoriesFile("forms.stories.js", "Forms", formNames);
const componentCount = writeStoriesFile(
  "components.stories.js",
  "Components",
  componentNames
);

console.log(
  `Wrote ${shellCount} shell + ${formCount} forms + ${componentCount} component stories → stories/`
);
