#!/usr/bin/env node
/**
 * Generates one CSF3 story file per component under stories/<category>/.
 * Docs source uses the packaged .demo fragment (not Storybook chrome).
 */
import fs from "node:fs";
import path from "node:path";
import {
  root,
  componentsDir,
  listComponents,
  categorize,
  extractTemplate,
  toPascalCase,
  toStoryTitle,
  INTERACTIVE,
} from "./lib/components.mjs";

const storiesDir = path.join(root, "stories");

function readHtml(name) {
  const htmlPath = path.join(componentsDir, name, `${name}.html`);
  if (!fs.existsSync(htmlPath)) return "";
  return fs.readFileSync(htmlPath, "utf8");
}

function slugCategory(category) {
  return category.toLowerCase().replace(/\s+/g, "-");
}

function writeStory(category, name) {
  const html = readHtml(name);
  if (!html) return false;

  const fragment = extractTemplate(html);
  const title = toStoryTitle(category, name);
  const exportName = "Default";
  const hasPlay = INTERACTIVE.has(name);
  const dir = path.join(storiesDir, slugCategory(category));
  fs.mkdirSync(dir, { recursive: true });

  const lines = [
    `/* AUTO-GENERATED by scripts/generate-stories.mjs — do not edit by hand */`,
    `import { renderComponent, playComponent } from "../render.js";`,
    ``,
    `export default {`,
    `  title: ${JSON.stringify(title)},`,
    `  tags: ["autodocs"],`,
    `  parameters: {`,
    `    layout: "fullscreen",`,
    `    docs: {`,
    `      description: {`,
    `        component: ${JSON.stringify(
      `**${name}** — barebones markup you can style. Source: \`components/${name}/\``
    )},`,
    `      },`,
    `      source: {`,
    `        language: "html",`,
    `        code: ${JSON.stringify(fragment)},`,
    `        type: "code",`,
    `      },`,
    `    },`,
    `  },`,
    `};`,
    ``,
    `export const ${exportName} = {`,
    `  name: "Default",`,
    `  render: () => renderComponent(${JSON.stringify(name)}),`,
    ...(hasPlay
      ? [
          `  play: async ({ canvasElement }) => {`,
          `    await playComponent(${JSON.stringify(name)}, canvasElement);`,
          `  },`,
        ]
      : []),
    `};`,
    ``,
    // Keep a named export matching the component for deep links
    `export const ${toPascalCase(name)} = Default;`,
    ``,
  ];

  fs.writeFileSync(path.join(dir, `${name}.stories.js`), lines.join("\n"));
  return true;
}

function clearGeneratedStories() {
  if (!fs.existsSync(storiesDir)) return;
  for (const entry of fs.readdirSync(storiesDir, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith(".stories.js")) {
      fs.unlinkSync(path.join(storiesDir, entry.name));
    }
    if (entry.isDirectory() && entry.name !== "assets") {
      const dir = path.join(storiesDir, entry.name);
      for (const file of fs.readdirSync(dir)) {
        if (file.endsWith(".stories.js")) {
          fs.unlinkSync(path.join(dir, file));
        }
      }
      // remove empty category dirs later if needed
    }
  }
}

const names = listComponents().filter((n) => {
  // Skip CSS-only modules without HTML stories
  return fs.existsSync(path.join(componentsDir, n, `${n}.html`));
});
const groups = categorize(names);

fs.mkdirSync(storiesDir, { recursive: true });
clearGeneratedStories();

let total = 0;
for (const [category, list] of Object.entries(groups)) {
  for (const name of list) {
    if (writeStory(category, name)) total += 1;
  }
}

console.log(
  `Wrote ${total} per-component stories across ${Object.keys(groups).length} groups → stories/`
);
